
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:heliumdb}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.secret=KISY/71kLUVj1Ii4wcwCWjBesJdVmdBBKqTk5c077EE=

server.port=8080
